---
language: csharp
solution: ProjectIO.sln
install:
  - nuget restore ProjectIO.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ProjectIO.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Test/bin/Release/ProjectIO.Test.dll