---
language: csharp
solution: CMakeParser.sln
install:
  - nuget restore CMakeParser.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CMakeParser.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Test/bin/Release/Test.dll